### ISSUE TITLE
Error: ENAMETOOLONG: name too long

### ISSUE THREAD

**Issue by Thoughtyness** [RealFaviconGenerator/realfavicongenerator#365]
When I was trying to install my favicons on my node.js server I got to step 4.
4. Generate your icons:
mkdir outputDir
real-favicon generate faviconDescription.json faviconData.json outputDir

When I ran the final command I received this error:

Carters-MBP:blender thoughtyness$ real-favicon generate faviconDescription.json faviconData.json outputDir
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENAMETOOLONG: name too long, open '103,472 characters of icon data'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.exports.fileToBase64Sync (/usr/local/lib/node_modules/cli-real-favicon/node_modules/rfg-api/index.js:35:15)
    at Object.exports.normalizeMasterPicture (/usr/local/lib/node_modules/cli-real-favicon/node_modules/rfg-api/index.js:189:47)
    at Object.exports.normalizeAllMasterPictures (/usr/local/lib/node_modules/cli-real-favicon/node_modules/rfg-api/index.js:218:38)
    at Object.exports.normalizeAllMasterPictures (/usr/local/lib/node_modules/cli-real-favicon/node_modules/rfg-api/index.js:221:38)
    at Object.exports.createRequest (/usr/local/lib/node_modules/cli-real-favicon/node_modules/rfg-api/index.js:254:38)
    at /usr/local/lib/node_modules/cli-real-favicon/real-favicon-generate.js:32:21
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)

Is there any reason to generate the images when I have already downloaded them in the icon image package, meant for LAMP servers?

**Comment by phbernard** [comment]
I just went through the procedure and I can't reproduce the issue.

The message `103,472 characters of icon data` suggests a confusion between content and file file name, do you have an idea of where that could come from? Can you reproduce the content of your `faviconDescription.json`?
